name: Build

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run package
        run: make

      - name: Upload package (tar.gz)
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: target/project-files.tar.gz
          label: Project files (tar.gz)

      - name: Upload package (zip)
        uses: klakegg/github-upload@v0.9.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: target/project-files.zip
          label: Project files (zip)